In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [5]:
df2 = df.copy()

In [9]:
# Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]
df2

    Id          Name   Age Country   Gender   Income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:

df2.rename(index={0: "first"})

       Id          Name   Age Country   Gender   Income
first   1      John Doe  29.0     USA     Male  55000.0
1       1      John Doe  29.0     USA     Male  55000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0
3       3          Alex   NaN     USA  Unknown  47000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
5       5        Li Wei  27.0   China     Male  51000.0
6       6           NaN  45.0   India   Female  73000.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0

In [19]:
df2.rename(columns={"Income": "Salary"})

    Id          Name   Age Country   Gender   Salary
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
df2.sort_values("Salary")

    Id          Name   Age Country   Gender   Salary
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
3    3          Alex   NaN     USA  Unknown  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
1    1      John Doe  29.0     USA     Male  55000.0
0    1      John Doe  29.0     USA     Male  55000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
6    6           NaN  45.0   India   Female  73000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN

In [24]:
# Sorting - values & index
df2.sort_values("Salary")                     # sort values in ascending
df2.sort_values("Salary", ascending=False)    # sort values in descending
df2.sort_values(["Age", "Salary"])            # sorts for age, if age is same then sorts for income 

sorted_df2 = df2.sort_values(["Age", "Salary"])
sorted_df2.sort_index()

    Id          Name   Age Country   Gender   Salary
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [25]:
# Reset Index
sorted_df2.reset_index()
sorted_df2.reset_index(drop=True)     # to drop original index vals

    Id          Name   Age Country   Gender   Salary
0    5        Li Wei  27.0   China     Male  51000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    1      John Doe  29.0     USA     Male  55000.0
3    8    Rachel Lee  29.0     USA   Female  62000.0
4   10   Emily Davis  31.0     USA      NaN  58000.0
5    4  Maria Garcia  34.0   Spain   Female      NaN
6    7    Ahmed Khan  38.0     NaN     Male  68000.0
7    6           NaN  45.0   India   Female  73000.0
8    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
9    3          Alex   NaN     USA  Unknown  47000.0
10   2    Jane Smith   NaN  Canada   Female  62000.0

In [27]:
# Ranking
df2["Ranking"] = df2["Salary"].rank(ascending=False, method="dense")

In [29]:
# Reorder
df2[["Id", "Name", "Age", "Salary", "Gender", "Country", "Ranking"]]

    Id          Name   Age   Salary   Gender Country  Ranking
0    1      John Doe  29.0  55000.0     Male     USA      5.0
1    1      John Doe  29.0  55000.0     Male     USA      5.0
2    2    Jane Smith   NaN  62000.0   Female  Canada      3.0
3    3          Alex   NaN  47000.0  Unknown     USA      7.0
4    4  Maria Garcia  34.0      NaN   Female   Spain      NaN
5    5        Li Wei  27.0  51000.0     Male   China      6.0
6    6           NaN  45.0  73000.0   Female   India      1.0
7    7    Ahmed Khan  38.0  68000.0     Male     NaN      2.0
8    8    Rachel Lee  29.0  62000.0   Female     USA      3.0
9    9   Carlos Ruiz   NaN  45000.0     Male  Mexico      8.0
10  10   Emily Davis  31.0  58000.0      NaN     USA      4.0